
/** \file	mpx.c
 *  \brief	MPX Main File
 *
 * 	This file contains the start-of-execution, i.e. function main(), for MPX.
 *
**/

/* Author: Paul Prince <paul@littlebluetech.com>
 *
 * Version-control information is managed by Git, and hosted by GitHub:
 *	- Website:	https://github.com/pprince/cs450
 *	- Public Repo:	git://github.com/pprince/cs450.git
 *	- Comitters:	git@github.com:pprince/cs450.git
 *
 * Documentation for developers is generated by Doxygen; for detailed
 * information about the files, functions, data structures, etc. that
 * make up MPX and how they relate to each other, refer to:
 *
 * 	"MPX Programmer's Manual"
 *
 * which can be found in the doc/ directory, or re-generated by running:
 *
 * 	`doxygen doxygen_config`
 *
 * from the top-level repository directory.
 *
**/


#include "mpx_supt.h"
#include "mpx_util.h"
#include "mpx_sh.h"
#include "mpx_cmds.h"


/** This is the start-of-execution for the MPX executable. */
void main(int argc, char *argv[]) {

	sys_init( MODULE_R1 );	/* System-specific initialization.		*/
	init_commands();	/* Initialization for MPX user commands.	*/
	mpx_shell();		/* Execute the command-handler loop.		*/


	/* mpx_shell() should never return, so if we get here, then
	 * we should exit with error status. */
	printf("FATAL ERROR: mpx_shell() returned! That should never happen...\n");
	sys_exit();	/* Terminate, after doing MPX-specific cleanup. */
}
