
/** \file	mpx_sh.c
 *  \brief	MPX Shell, aka Command Handler
 *
 * 	This file contains the functions etc. to implement the user interface for MPX.
 *
**/

/* Author: Paul Prince <paul@littlebluetech.com>
 *
 * Version-control information is managed by Git, and hosted by GitHub:
 *	- Website:	https://github.com/pprince/cs450
 *	- Public Repo:	git://github.com/pprince/cs450.git
 *	- Comitters:	git@github.com:pprince/cs450.git
 *
 * Documentation for developers is generated by Doxygen; for detailed
 * information about the files, functions, data structures, etc. that
 * make up MPX and how they relate to each other, refer to:
 *
 * 	"MPX Programmer's Manual"
 *
 * which can be found in the doc/ directory, or re-generated by running:
 *
 * 	`doxygen doxygen_config`
 *
 * from the top-level repository directory.
 *
**/


#include "supt/mpx_supt.h"
#include "mpx_util.h"


/** This function implements the MPX shell (command-line user interface).
 *
 * mpx_shell() never returns!
 *
 */
void mpx_shell(void) {

	/** A buffer to hold the command line input by the user.
	 *  We include space for the \r, \n, and \0 characters, if any. */
	char cmdline[MAX_LINE+2];

	/** Buffer size argument for passing to sys_req(). */
	int line_buf_size = MAX_LINE;

	/** Used to capture the return value of sys_req(). */
	int err;

	for(;;) { /* Loop Forever */
		sys_req( READ, TERMINAL, cmdline, &line_buf_size );
		printf("[cmdline]\n");
	}
}
