
/** \file	mpx_util.c
 *  \brief	Various utility functions used by all of MPX.
 *
 * 	This file contains the functions etc. to implement the user interface for MPX.
 *
**/

/* Author: Paul Prince <paul@littlebluetech.com>
 *
 * Version-control information is managed by Git, and hosted by GitHub:
 *	- Website:	https://github.com/pprince/cs450
 *	- Public Repo:	git://github.com/pprince/cs450.git
 *	- Comitters:	git@github.com:pprince/cs450.git
 *
 * Documentation for developers is generated by Doxygen; for detailed
 * information about the files, functions, data structures, etc. that
 * make up MPX and how they relate to each other, refer to:
 *
 * 	"MPX Programmer's Manual"
 *
 * which can be found in the doc/ directory, or re-generated by running:
 *
 * 	`doxygen doxygen_config`
 *
 * from the top-level repository directory.
 *
**/

#include "mpx_util.h"
#include "supt/mpx_supt.h"



