
/** \file	mpx_cmds.c
 *  \brief	MPX User Commands
 *
 * 	This file implements each of the user commands for MPX.
 *
**/

/* Author: Paul Prince <paul@littlebluetech.com>
 *
 * Version-control information is managed by Git, and hosted by GitHub:
 *	- Website:	https://github.com/pprince/cs450
 *	- Public Repo:	git://github.com/pprince/cs450.git
 *	- Comitters:	git@github.com:pprince/cs450.git
 *
 * Documentation for developers is generated by Doxygen; for detailed
 * information about the files, functions, data structures, etc. that
 * make up MPX and how they relate to each other, refer to:
 *
 * 	"MPX Programmer's Manual"
 *
 * which can be found in the doc/ directory, or re-generated by running:
 *
 * 	`doxygen doxygen_config`
 *
 * from the top-level repository directory.
 *
**/


#include "mpx_cmds.h"
#include "mpx_supt.h"
#include "mpx_util.h"
#include <string.h>


static struct mpx_command *list_head = NULL;

void add_command( char *name, void (*function)(int argc, char *argv[]) ){

	/* Temporary variable for iterating through the list of commands. */
	struct mpx_command *this_command;

	/* Allocate space for the new command structure. */
	struct mpx_command *new_command = sys_alloc_mem(sizeof(struct mpx_command));
		/* FIXME: check for malloc failure! */

	/* Initialize the structure. */
	strcpy( new_command->name, name );
	new_command->function = function;
	new_command->next = NULL;

	/* Insert the new command into the list of commands. */
	this_command = list_head;
	if ( this_command == NULL ) {
		list_head = new_command;
	} else {
		while ( this_command->next != NULL ){
			this_command = this_command->next;
		}
		this_command->next = new_command;
	}
}

void mpxcmd_commands( int argc, char *argv[] ) {

	/* Temporary variable for iterating through the list of commands. */
	struct mpx_command *this_command = list_head;

	while( this_command != NULL ) {
		printf("        %s\n", this_command->name);
	}
}

void init_commands(void) {
	add_command("commands", mpxcmd_commands);
}
