
/** \file	mpx_util.c
 *  \brief	Various utility functions used by all of MPX.
 *
 * 	This file contains the functions etc. to implement the user interface for MPX.
 *
**/

/* Author: Paul Prince <paul@littlebluetech.com>
 *
 * Version-control information is managed by Git, and hosted by GitHub:
 *	- Website:	https://github.com/pprince/cs450
 *	- Public Repo:	git://github.com/pprince/cs450.git
 *	- Comitters:	git@github.com:pprince/cs450.git
 *
 * Documentation for developers is generated by Doxygen; for detailed
 * information about the files, functions, data structures, etc. that
 * make up MPX and how they relate to each other, refer to:
 *
 * 	"MPX Programmer's Manual"
 *
 * which can be found in the doc/ directory, or re-generated by running:
 *
 * 	`doxygen doxygen_config`
 *
 * from the top-level repository directory.
 *
**/

#include "mpx_util.h"
#include "mpx_supt.h"
#include <string.h>

/** Removes trailing newline, if any.
 *
 * This function checks to see if the last character in a string is a newline, and, if so, removes it.
 * Otherwise, the string is left unchanged.
 *
 * The input must be a valid (allocated and null-terminated) C string, otherwise the results are undefined
 * (but will most likley result in a segmentation fault / protection fault).
 *
 * Returns the number of characters removed from the string.
 */
int mpx_chomp ( char *str /**< The string to chomp. */ ){
	if( strlen(str) > 0 ){
		if( str[ strlen(str)-1 ] == '\n' ){
			str[ strlen(str)-1 ] = '\0';
			return 1;
		}
	}
	return 0;
}

